services:
  app:
    container_name: app-frontend
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${VITE_PORT:-8080}:8019"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true