/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoaderComponent: typeof import('./components/LoaderComponent.vue')['default']
    ModalConfirmationComponent: typeof import('./components/ModalConfirmationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleComponent: typeof import('./components/TitleComponent.vue')['default']
  }
}
